<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Sure in Sure - автострахование");
$APPLICATION->SetPageProperty("NOT_SHOW_NAV_CHAIN", "Y");
$APPLICATION->SetTitle("Главная страница");
?><?$APPLICATION->IncludeComponent("nzr:suin", ".default", array(
	"REQUIRE" => array(
		0 => "mark",
		1 => "model",
		2 => "year",
		3 => "power",
		4 => "litr",
		5 => "cost",
		6 => "credit",
		7 => "credit_bank",
		8 => "people-type",
		9 => "people-num",
		10 => "people-gender",
		11 => "people-year",
		12 => "people-driving",
		13 => "rudder",
		14 => "date",
		15 => "risk",
		16 => "franshiza",
		17 => "repair",
	),
	"MARKS_IBLOCK_TYPE" => "suin",
	"MARKS_IBLOCK_ID" => "10",
	"MARKS_SORT_BY" => "NAME",
	"MARKS_SORT_ORDER" => "ASC",
	"MODELS_IBLOCK_TYPE" => "suin",
	"MODELS_IBLOCK_ID" => "11",
	"MODELS_SORT_BY" => "NAME",
	"MODELS_SORT_ORDER" => "ASC",
	"MODELS_MARK" => "MARK",
	"YEAR_START" => "2006",
	"RESULT_IBLOCK_TYPE" => "suin",
	"RESULT_IBLOCK_ID" => "12",
	"RESULT_PROPERTY" => "RESULT",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "Y",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "Y",
	"CACHE_GROUPS" => "Y",
	"HELP_IBLOCK_TYPE" => "text",
	"HELP_IBLOCK_ID" => "13",
	"HELP_MARK" => "4057",
	"HELP_MODEL" => "4057",
	"HELP_YEAR" => "4059",
	"HELP_POWER" => "4062",
	"HELP_LITR" => "4063",
	"HELP_COST" => "4033",
	"HELP_CREDIT" => "",
	"HELP_CREDIT_BANK" => "",
	"HELP_PEOPLE-TYPE" => "",
	"HELP_PEOPLE-NUM" => "",
	"HELP_PEOPLE-GENDER" => "",
	"HELP_PEOPLE-YEAR" => "",
	"HELP_PEOPLE-DRIVING" => "",
	"HELP_RUDDER" => "",
	"HELP_DATE" => "4070",
	"HELP_RISK" => "4038",
	"HELP_FRANSHIZA" => "",
	"AJAX_OPTION_ADDITIONAL" => ""
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>